### ISSUE TITLE
Convert IEEE identifier in ISO or ISO/IEEE mixed format to IEEE format

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#112]
Examples:
- `IEEE Unapproved Draft Std 16326:2009` should become `IEEE Unapproved Draft Std 16326-2009`
- `ISO/IEC/IEEE 31320-1:2012 (Adoption of IEEE Std 1320.1-1998)` to `ISO/IEC/IEEE 31320-1-2012 (Adoption of IEEE Std 1320.1-1998)`

**Comment by mico** [comment]
@ronaldtse I believe identifiers like `IEC/IEEE 60214-2:2019` we should keep in ISO format, I'm I right?

**Comment by mico** [comment]
Original identifier `IEC/IEEE 60214-2:2019` can be found on "IEC" website.
On IEEE website it appears in different formats (ISO and IEEE):
<img width="423" alt="image" src="https://github.com/metanorma/pubid-ieee/assets/5849/75211295-1d3b-43bf-84d2-b03388766712">
<img width="468" alt="image" src="https://github.com/metanorma/pubid-ieee/assets/5849/6cc82525-553b-4580-8c03-90f77a4ee627">

@ronaldtse Should we convert this identifiers to "IEEE" format as well?

**Comment by ronaldtse** [comment]
@mico maybe we should define an "ISO-style" stage in IEEE identifier format, using the `D` draft prefix.

e.g.
`IEC/IEEE P63113 CD4, April 2019` => `IEC/IEEE P63113/DCD4, April 2019`

So this is purely IEEE.

**Comment by ronaldtse** [comment]
> Original identifier `IEC/IEEE 60214-2:2019` can be found on "IEC" website.
> 
> On IEEE website it appears in different formats (ISO and IEEE): <img alt="image" width="423" src="https://private-user-images.githubusercontent.com/5849/320774003-75211295-1d3b-43bf-84d2-b03388766712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTI5NzYsIm5iZiI6MTcxMjY1MjY3NiwicGF0aCI6Ii81ODQ5LzMyMDc3NDAwMy03NTIxMTI5NS0xZDNiLTQzYmYtODRkMi1iMDMzODg3NjY3MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDg1MTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA5MzBkZDA4MTBhMDgyNGNlNTcyYTY5YjkxYmI5N2RkY2U5ZmQ4ZDI5Njg5M2FlMzM4MTRmNGMyNjNhMDFjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pBSi9XXTx5JjT8EeJ7OsnMfHyiBbvpKJt8-qem_4RbA"> <img alt="image" width="468" src="https://private-user-images.githubusercontent.com/5849/320774100-6cc82525-553b-4580-8c03-90f77a4ee627.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTI5NzYsIm5iZiI6MTcxMjY1MjY3NiwicGF0aCI6Ii81ODQ5LzMyMDc3NDEwMC02Y2M4MjUyNS01NTNiLTQ1ODAtOGMwMy05MGY3N2E0ZWU2MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMDg1MTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlmM2VmMTU5YmM5ZjliN2ViZjEzNTEyOWQwZjIyZTFiYWRhM2M1OTRiMGRmZjIwZjU1ZGU5ZTM5ODZmYTM2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HnQXQ8t-7FZ-AmnGYDR_1MNLoK2z2j51sCgQRzBixN8">
> 
> @ronaldtse Should we convert this identifiers to "IEEE" format as well?

I think so, you're right here. Let's use "IEEE/IEC 60214-2-2019" for IEEE.

**Comment by mico** [comment]
> I think so, you're right here. Let's use "IEEE/IEC 60214-2-2019" for IEEE.

@ronaldtse Should we convert "IEC/IEEE 60214-2:2019" to "IEEE/IEC 60214-2-2019" or we convert it only when it starts with "IEEE" eg. "IEC/IEEE 60214-2:2019"

**Comment by mico** [comment]
> @mico maybe we should define an "ISO-style" stage in IEEE identifier format, using the `D` draft prefix.
> 
> e.g. `IEC/IEEE P63113 CD4, April 2019` => `IEC/IEEE P63113/DCD4, April 2019`
> 
> So this is purely IEEE.

@ronaldtse Why we don't keep it in currently implemented IEEE style? eg. "IEC/IEEE P63113/CD4, April 2019"
Without "D" prefix it is visually better, easier to read (something like "/DDIS" looks a little weird).
We can just assume everything after slash is a draft stage if it's not a defined entity like Amendment or Corrigenda.
What do you think about it?

**Comment by opoudjis** [comment]
The point here is to convert identifiers to a format that IEEE recognises. I would also convert identifiers that started with IEC/IEEE, as IEEE is still interested in them; and I would not reorder IEC/IEEE to IEEEE/IEC, since that ordering is already decided by the first publisher, and IEEE cannot change the identifier that radically.

Because the point is to keep things familiar to IEEE users, my opinion is that a new D prefix is a terrible idea: they will not be able to guess what it is about, and it is needlessly leading to confusion—to the extent it will likely be rejected by the IEEE. If we are going to put draft stage information into these IEEE-style identifiers at all, we should be as explicit about it as possible: I would suggest `IEC/IEEE P63113 draft CD4, April 2019. At least "draft CD4" is not forcing IEEE users to work out what is going on.

**Comment by mico** [comment]
> `IEC/IEEE P63113 draft CD4, April 2019. At least "draft CD4"

`IEC/IEEE Draft Std P63113/CD4, April 2019` - that how it is supposed to be already in IEEE format, a “draft” word already there

**Comment by mico** [comment]
@ronaldtse @opoudjis there are identifiers in ISO format like `IEEE/ISO/IEC 8802-3:2021/Amd 4-2021`

For IEEE format identifiers we don't have amendments with number and year, there are only amendments without number and year, like `ANSI C63.4a-2017 (Amendment to ANSI C63.4-2014)`, `IEEE Std 802.3ba-2010 (Amendment to IEEE Standard 802.3-2008)`, `IEEE P802.3bk/D3.0, March 2013 (Amendment of IEEE Std 802.3-2012)`.

Amendment's numbering in IEEE format are different from ISO amendments (they use letters in identifiers number, like "a" in ANSI C63.4a-2017) so I'm not sure if it will be correct to just reformat `IEEE/ISO/IEC 8802-3:2021/Amd 4-2021` to something like `IEEE/ISO/IEC Std 8802-3-2021/Amd 4-2021`. Or just keep it in original ISO format?

**Comment by mico** [comment]
@ronaldtse should identifier `ISO/IEC/IEEE CD P26513/D1, August 2015` have draft version and ISO stage at the same time?
Will it be correct to render it as `ISO/IEC/IEEE Std Draft P26513/CD1, August 2015`?

**Comment by opoudjis** [comment]
Guys, I don't have a sense of where this requirement came from, and it increasingly seems to be a bad idea to me. There is going to be a myriad places where the information  model of ISO and IEEE identifiers deviate, and @ronaldtse you need to make a blanket rule, rather than adjudicate individual cases: when an ISO identifier has a model difference from the IEEE identifier, do we really treat it like an IEEE identifier, or do we let ISO features in to the IEEE identifier?

Because if we *really* are treating these identifiers like IEEE identifiers, then we should be ignoring numbers and years of amendments (which means amendments ambiguous), and we should be ignoring ISO stages.

if this is a requirement we made up and not IEEE, then drop this, because it is stupid. If ISO produced an identifier for the document, and IEEE did not bother to come up with its own identifier, then we have zero business guessing what a hypothetical identifier should be.

If this is a requirement from IEEE, and it is existing practice, it is IEEE's job, not ours, to come up with what the rules are for transforming ISO identifiers to IEEE, and IEEE will have already done so.

If this is a requirement from IEEE, and they have never done it, and they want us to come up with the rules, then they are irresponsible, and in my opinion our identifiers should look like ISO as much as possible (so jam in numbers and years of amendments and ISO stages wherever it looks like they'll fit), because the more different the ISO and IEEE format identifiers are, the more potential for trouble we are raising.

I can't give you answers, @mico, because I don't have the business context for this. The last paragraph is my opinion if we have to come up with a rule, but my real opinion is that this is a bad idea, and we should be doing nothing without explicit IEEE sign-off.

**Comment by opoudjis** [comment]
Because I do not understand the business requirement, and I think this is naive to be doing without IEEE feedback, I am not going to review the PR for this. The test cases look plausible enough, especially now you are no longer pursuing the utterly bizarre recommendation of a "DCD4" stage identifier (which nobody in IEEE would ever understand). But there are a whole lot of edge cases where this will simply not work.

Shrug. Proceed with this, but without IEEE feedback, you are going to do things they will ask you to undo.
