### ISSUE TITLE
Two dates in IEEE identifiers

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#115]
Identifier `IEEE 16085-2020`:

https://ieeexplore.ieee.org/document/9373052/versions#versions

![image](https://github.com/metanorma/pubid-ieee/assets/5849/6ff76a3e-2540-4148-9506-cb0ada2c2542)
what these 2 dates in identifiers means?

![image](https://github.com/metanorma/pubid-ieee/assets/5849/203ae1b7-035f-4257-97cd-7d5530f2ce92)

`Date of Publication: 15 January 2021`
So `2020` is not publication date, but what is that, edition date?

**Comment by ronaldtse** [comment]
@mico likely the IEEE side assigned it a 2020 number but it got published later in 2021.

Is this significant?

**Comment by opoudjis** [comment]
We have here an arbitrarily assigned, nominal publication date, assigned ahead of time; and a real life publication date, where the schedule of publication slipped.

If you are reconstructing the document history, the actual publication date matters. For the purposes of document identifiers, I believe it does not matter: we treat the assigned publication date as the only publication date, because after all it is the only date that makes it into the identifier.

**Comment by opoudjis** [comment]
Does this issue need to remain open?
