### ISSUE TITLE
Clarification request for identifiers published date, draft date, edition date.

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#116]
For drafts we have date:
`IEEE Draft Std P802.1AX-REV/D4.0, March 2014`
But also we have date for identifiers with ISO stage, like:
`IEEE Unapproved Draft Std P12207/FDIS, Nov 2007`
Sometimes without stage or draft but it have date:
`IEEE/IEC P60076-57-1202, July 2014`
Sometimes there are just year:
`IEEE Std 1491-2012`
Also we have edition date I didn't mentioned:
`IEC 61691-7 Edition 1.0 2009-12`

Is the draft date and identifier with ISO stage (now considered as draft) are the same?
When identifier without draft or stage have date is it publication date? Publication date and draft date are not the same, right? And all these are not related to edition date?

Currently for IEEE we have:
- draft date
- publication date
- edition date

**Comment by mico** [comment]
> IEEE/IEC P60076-57-1202/D{draft id}, July 2014

@ronaldtse Does it means that when we have date in identifier, like ", July 2014" at the end, it is draft, right?
But when we have only year as in identifier `IEEE Std 16085-2020` that doesn't mean it's draft, is it correct?

> > Also we have edition date I didn't mentioned: `IEC 61691-7 Edition 1.0 2009-12`
> 
> Edition is "1.0". Publication date is "2009-12".

Should we reformat it as `IEC 61691-7 Edition 1.0, December 2009`?

> > Is the draft date and identifier with ISO stage (now considered as draft) are the same?
> 
> What do you mean? I don't understand this question.

Identifiers with ISO stage usually also have publication date, should it be considered as "draft date"?

> Actually, every document only has 1 date, which is the date this document is "offered".
> 
> published document => has publication date, which is also edition date. draft document => has draft date.

Should we use only "publication date" for any types of dates like edition date, draft date, publication date?
Now edition date, publication date and draft date are different attributes.

**Comment by opoudjis** [comment]
I'm coming in to this with little context, but, to confirm:

* draft date is indeed date of publication (or circulation pending endorsement) of a draft of a document. 
* edition date is date of publication of a specific edition of a document.
* There is a point in storing both pieces of information in a bibliographic record, because that gives the history of a document. But for identifiers, don't you only ever publish one date at a time? Does this have formatting implications?

> But also we have date for identifiers with ISO stage, like:
> IEEE Unapproved Draft Std P12207/FDIS, Nov 2007

Yes, that is a draft date, since it is the date of publication of a draft of a document, and the identifier is explicitly saying that.

It is *usual* for the date of publication of a document to be year, and the date of draft to be month or even month and day; that's because you can have many drafts of a document issued in a year, but I don't think I've seen a case where there are two different publications/editions of a document in a year.

That said, BSI we have cases where some classes of document include the month in  a publication date, and some do not.  I really think you should only infer draft vs publication status of a document from whether the document is said to be a date. Yes, I would be surprised if a month is given for a publication date, but it is not impossible: BSI does it.

> Should we use only "publication date" for any types of dates like edition date, draft date, publication date?
Now edition date, publication date and draft date are different attributes.

Like I said: there's a reason bibliographic entries differentiate them, but I would be very surprised if any standards identifier uses more than one date. Drafts don't have  a publication date. Published documents don't care in their identifier about draft dates. Edition dates usually override first publication dates. The only case where we routinely see two dates is in amendments and corrigenda, where you have a date of publication of the original document, vs a date of publication of the amendment.

Only model these as different dates if you have an identifier that uses two of them, or if the formatting requirements are different. The month status of drafts, I think, is inherited from the document being a  draft, not from the date being differently formatted.

**Comment by mico** [comment]
> Do you think we can just use 1 "date" to handle? Unless we have multiple dates in one PubID?

@ronaldtse My question is more about, did I make a mistake using 3 different dates for draft, edition, and publication?
I'm fine with all them using separate attributes, but maybe separate attributes for draft date and publication date are too much?

**Comment by ronaldtse** [comment]
@mico its not a mistake per se but it’s difficult to determine the type of date accurately in the identifier, and hence difficult to use. Better stick with one date.

**Comment by opoudjis** [comment]
Does this ticket need to stay open, @mico?

**Comment by mico** [comment]
> Unless we have multiple dates in one PubID?

`IEC/IEEE 62582-1:2011 Edition 1.0 2011-08`

This should be converted to IEEE format, then it will be `IEC/IEEE Std 62582-1-2011 Edition 1.0 2011-08`
Twice mentioned the same year. 

<img width="533" alt="image" src="https://github.com/metanorma/pubid-ieee/assets/5849/d1c0ed8c-ca0a-468d-be7e-770ae6e8b717">

Year 2011 was the part of identifier but later on it was removed. I'm not sure how to approach this case.
Could anything from these work?

- `IEC/IEEE Std 62582-1-2011`
- `IEC/IEEE Std 62582-1-2011 Edition 1.0`
- `IEC/IEEE Std 62582-1, August 2011 Edition 1.0`

**Comment by opoudjis** [comment]
So in IEC/IEEE Std 62582-1-2011 Edition 1.0 2011-08 (wherever the hell that came from), there is a year date for the standard, and a year + month date for the edition. They are not in fact different years, they are different granularities of the same year, and if the next edition were published in May 2024, it would turn into IEC/IEEE Std 62582-1-2024 Edition 2.0 2024-05. You are not going to get IEC/IEEE Std 62582-1-2011 Edition 2.0 2024-05, that is not how those dates work. The dates in fact indicate the edition in ISO practice (which IEC inherits), and the edition date is merely an elaboration of that.

IEC/IEEE Std 62582-1-2011 Edition 1.0 2011-08 seems to me to be preferable to the last two alternatives, but it is your job to investigate IEEE possible identifier formats: I have no idea what IEEE expect to see, and I don't have access to any more information than you do via Google. I am not willing to make stuff up that a client will turn around and tells us is wrong.
