### ISSUE TITLE
Parse documents with edition

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#31]
Identifiers with edition:

```
ISO/IEC 15288 First edition 2002-11-01
IEC 61588:2009(E)
IEEE/ISO/IEC P90003, February 2018 (E)
ANSI/IEEE Std 802.1D, 1998 Edition
IEC 61671-2 Edition 1.0 2016-04
IEC 62525-Edition 1.0 - 2007
IEC/IEEE 60076-16 Edition 2.0 2018-09
IEEE Std 1003.1, 2004 Edition
IEC 62659 Ed.1, October 2011
```

There might be other patterns for edition, need to investigate more.

**Comment by ronaldtse** [comment]
Agree.

**Comment by mico** [comment]
@ronaldtse I found that identifiers with edition year only (no month or date) formatted differently:
```
IEC 62525-Edition 1.0 - 2007
IEEE Std 1003.1, 2004 Edition
```

The last one more common, the first one appears only once.
Right now I render these identifiers as:
```
IEC 62525 Edition 1.0 2007
IEEE Std 1003.1 Edition 2004
```

I'm not sure where did this pattern come up from, maybe I just removed "month" part without investigating it.
I don't feel it's right, seems we should render these as:
```
IEC 62525 2007 Edition
IEEE Std 1003.1 2004 Edition
```

But what if it's not first edition? And actually I don't know what edition number we have for `IEEE Std 1003.1, 2004 Edition`.

**Comment by ronaldtse** [comment]
IEEE published documents have an "edition year":
* "IEEE Std 1003.1 2004 Edition" => "IEEE Std 1003.1-2004" is the correct format

The first one "IEC 62525-Edition 1.0 - 2007" is very strange. It should likely be (one-off) renamed to "IEC 62525:2007". But IEEE should not have IEC references anyway... and it can no longer be found online!

Maybe we should just drop this one because:

This search result:
<img width="650" alt="Screen Shot 2023-02-08 at 3 45 46 PM" src="https://user-images.githubusercontent.com/11865/217466330-308f0d35-84b1-47d3-b3eb-cc34f789181d.png">

Leads to:
<img width="959" alt="Screen Shot 2023-02-08 at 3 46 19 PM" src="https://user-images.githubusercontent.com/11865/217466446-c6dc6e56-56d7-499d-965d-ecd3d1d11133.png">
